name: Deploy to GitHub Pages

on:
  push:
    branches: [ merge2-Armandov3 ]  # Changed to your specific branch
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version your project requires
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # Deploy the root folder
          branch: merge2-Armandov3  # Changed: Deploy to the same branch
          clean: true  # Automatically remove deleted files from the deployment
          clean-exclude: |
            .git
            .github
            node_modules
            src
            public
            css
            img
            res